### ISSUE TITLE
点了应用没有反应

### ISSUE THREAD

**Issue by xiaoxuan1412** [harrynull/bilibili_blacklist#10]
开发者辛苦了，在微博看到了之后立马就使用了，顺便推荐了朋友们，但是点了应用后，在B站上并没有反应。。希望能够完善，加油ヾ(◍°∇°◍)ﾉﾞ

**Comment by harrynull** [comment]
原因是bilibili最近添加了添加弹幕屏蔽词API的反csrf验证。现在已经添加了相关支持，请尝试~
