### ISSUE TITLE
Firefox浏览器OAuth登录兼容问题

### ISSUE THREAD

**Issue by harrynull** [harrynull/bilibili_blacklist#2]
提交人：知乎[@小so](https://www.zhihu.com/people/xiao-so-83/activities)
内容：火狐浏览器无法使用OAuth自动登录

**Comment by abc612008** [comment]
问题定位：firefox浏览器使用bilibili的登录接口时返回{code:-800,msg:"不安全的请求"}，暂时无法修复，建议使用手机扫描二维码

**Comment by harrynull** [comment]
由于OAuth网页登录开始判断UA并且全平台不可用，关闭issue。

**Comment by snowman** [comment]
如何电脑登录? 这样不就跟张小龙的微信一样要下载app扫码登录了吧?

**Comment by harrynull** [comment]
@snowman 你可以
1. 修改浏览器 UserAgent 为 bilibili 手机客户端；或者
2. 电脑上登录 bilibili.com 查看 Cookies 填写到相应的地方手动登录（Chrome: 地址栏左边的锁 - Cookies）

这个限制不是我做的，我也很讨厌手机扫码登录，下载的 app 也不是我自己的 app。

**Comment by snowman** [comment]
![bilibili-border](https://user-images.githubusercontent.com/16096559/159101468-c91dd704-61ea-4225-a943-b179c90198be.jpg)

<del>看来只能用 `Cookie` 登录了</del>
我刚才修改的是手机浏览器的 `User-Agent`,
我再试试 bilibili 客户端的 UA 

--
算了, 还是用 cookie 登录吧
