### ISSUE TITLE
如何从已有网站导入用户屏蔽数据?

### ISSUE THREAD

**Issue by wutong233** [harrynull/bilibili_blacklist#20]
如题

**Comment by harrynull** [comment]
"已有网站"指的是什么?

**Comment by wutong233** [comment]
> "已有网站"指的是什么?

比如你的网站https://harrynull.tech/bilibili/user.html

**Comment by harrynull** [comment]
如果你指的是使用的话，登录之后（二维码登录正在修复）点应用屏蔽按钮应该就可以了。

**Comment by harrynull** [comment]
如果还有问题的话麻烦 reopen 这个 issue。
