### ISSUE TITLE
设定需要每个点击启用吗？应该显示关闭还是启动？希望增加网页筛选，按屏蔽词数量排列

### ISSUE THREAD

**Issue by specked2527** [harrynull/bilibili_blacklist#43]
200多个手动点击启动
![收拾收拾](https://user-images.githubusercontent.com/124735279/236627510-507dd546-de0b-4e4c-a96c-7314d3bc45a6.png)
200多个手动点击启动

**Comment by harrynull** [comment]
我要是没记错的话这里的“关闭”是将其关闭，也就是说如果后面字是“关闭”的话，说明这条屏蔽词已经启用了。
