### ISSUE TITLE
网站现在进不去吗？

### ISSUE THREAD

**Issue by yangqi469** [harrynull/bilibili_blacklist#9]
Proxy Error
The proxy server could not handle the request GET /bilibili/.
Reason: Error during SSL Handshake with remote server

Apache/2.4.18 (Ubuntu) Server at harrynull.tech Port 443

**Comment by harrynull** [comment]
感谢提醒，已修复

**Comment by yangqi469** [comment]
@harrynull 服务器好像有坏掉了。
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.18 (Ubuntu) Server at harrynull.tech Port 443
是我本地网络的原因吗？

**Comment by harrynull** [comment]
不好意思，是我这里的问题，已修复
